### PR TITLE
Add example destination address

### PR DESCRIPTION
**Pull request by FredKSchott**
I got caught up here for a second because I didn't have a destination address. I'd suggest putting this testnet address is to help others.

### CODE REVIEW

**Review by intelliot — APPROVED** [review]
Is there significance to this address, or is it just a new random Testnet account?

I'll probably update this to use an X-address later on.

**Comment by FredKSchott** [comment]
No significance, just a random address generated on the testnet. Is it possible to generate an address that looks more fake, like `r0000000000000000000`?

**Review by intelliot — CHANGES_REQUESTED** [review]
Let's use `rPT1Sjq2YGrBMTttX4GZHjKu9dyfzbpAYe` as the destination; it is the faucet account. Sending to it will simply re-fill the faucet with the same fake xrp that it's sending out.

**Comment by FredKSchott** [comment]
Done! PTAL

**Review by intelliot — APPROVED** [review]
This address works on both altnets (Testnet and Devnet)

(The capitalization/space was recently officially changed to `Testnet` https://xrpl.org/xrp-testnet-faucet.html )

**Pull request merged**
